---
# vars file for openhpc
# note, it's best not to edit this by hand too much use the build-default-vars.sh script in the role root directory to generate this based on filtering yum list
# default install is for a minimual OpenHPC install, override the following to change
openhpc_install_standard: false
openhpc_install_gnu: false
openhpc_install_gnu7: false
openhpc_install_gnu8: false
openhpc_install_intel: false

openhpc_standard_packages:
  - cmake-ohpc
  - conman-ohpc
  - examples-ohpc
  - lmod-ohpc
  - losf-ohpc
  - lua-bit-ohpc
  - lua-filesystem-ohpc
  - lua-posix-ohpc
  - ohpc-base
  - ohpc-base-compute
  - ohpc-filesystem
  - pdsh-ohpc
  - pmix-ohpc
  - EasyBuild-ohpc
  - R_base-ohpc
  - autoconf-ohpc
  - automake-ohpc
  - charliecloud-ohpc
  - clustershell-ohpc
  - docs-ohpc
  - genders-compat-ohpc
  - genders-ohpc
  - hwloc-ohpc
  - libmxml1
  - libtool-ohpc
  - llvm4-compilers-ohpc
  - llvm5-compilers-ohpc
  - meta-packages
  - mrsh-ohpc
  - mrsh-rsh-compat-ohpc
  - mrsh-server-ohpc
  - msr-safe-ohpc
  - nhc-ohpc
  - nrpe-ohpc
  - ohpc-autotools
  - ohpc-buildroot
  - ohpc-release
  - papi-ohpc
  - paraver-ohpc
  - pdsh-mod-genders-ohpc
  - prun-ohpc
  - python-Cython-ohpc
  - python34-Cython-ohpc
  - shine-ohpc
  - singularity-ohpc
  - spack-ohpc
  - test-suite-ohpc
  - texlive-draftwatermark
  - texlive-draftwatermark-doc
  - texlive-everypage
  - texlive-everypage-doc
  - texlive-tcolorbox
  - texlive-tcolorbox-doc
  - texlive-trimspaces
  - texlive-trimspaces-doc
  - valgrind-ohpc
  - vim-clustershell-ohpc
openhpc_intel_packages:
  - adios-intel-impi-ohpc
  - adios-intel-mpich-ohpc
  - adios-intel-mvapich2-ohpc
  - adios-intel-openmpi-ohpc
  - adios-intel-openmpi3-ohpc
  - boost-intel-impi-ohpc
  - boost-intel-mpich-ohpc
  - boost-intel-mvapich2-ohpc
  - boost-intel-openmpi-ohpc
  - boost-intel-openmpi3-ohpc
  - dimemas-intel-impi-ohpc
  - dimemas-intel-mpich-ohpc
  - dimemas-intel-mvapich2-ohpc
  - dimemas-intel-openmpi3-ohpc
  - extrae-intel-impi-ohpc
  - extrae-intel-mpich-ohpc
  - extrae-intel-mvapich2-ohpc
  - extrae-intel-openmpi3-ohpc
  - geopm-intel-impi-ohpc
  - geopm-intel-mpich-ohpc
  - geopm-intel-mvapich2-ohpc
  - geopm-intel-openmpi3-ohpc
  - hdf5-intel-ohpc
  - hypre-intel-impi-ohpc
  - hypre-intel-mpich-ohpc
  - hypre-intel-mvapich2-ohpc
  - hypre-intel-openmpi-ohpc
  - hypre-intel-openmpi3-ohpc
  - imb-intel-impi-ohpc
  - imb-intel-mpich-ohpc
  - imb-intel-mvapich2-ohpc
  - imb-intel-openmpi-ohpc
  - imb-intel-openmpi3-ohpc
  - intel-compilers-devel-ohpc
  - intel-mpi-devel-ohpc
  - likwid-intel-ohpc
  - metis-intel-ohpc
  - mfem-intel-impi-ohpc
  - mfem-intel-mpich-ohpc
  - mfem-intel-mvapich2-ohpc
  - mfem-intel-openmpi3-ohpc
  - mpiP-intel-impi-ohpc
  - mpiP-intel-mpich-ohpc
  - mpiP-intel-mvapich2-ohpc
  - mpiP-intel-openmpi-ohpc
  - mpiP-intel-openmpi3-ohpc
  - mpich-intel-ohpc
  - mumps-intel-impi-ohpc
  - mumps-intel-mpich-ohpc
  - mumps-intel-mvapich2-ohpc
  - mumps-intel-openmpi-ohpc
  - mumps-intel-openmpi3-ohpc
  - mvapich2-intel-ohpc
  - netcdf-cxx-intel-impi-ohpc
  - netcdf-cxx-intel-mpich-ohpc
  - netcdf-cxx-intel-mvapich2-ohpc
  - netcdf-cxx-intel-openmpi-ohpc
  - netcdf-cxx-intel-openmpi3-ohpc
  - netcdf-fortran-intel-impi-ohpc
  - netcdf-fortran-intel-mpich-ohpc
  - netcdf-intel-impi-ohpc
  - netcdf-intel-mpich-ohpc
  - netcdf-intel-mvapich2-ohpc
  - netcdf-intel-openmpi-ohpc
  - netcdf-intel-openmpi3-ohpc
  - ocr-intel-ohpc
  - ohpc-intel-geopm
  - ohpc-intel-impi-io-libs
  - ohpc-intel-impi-parallel-libs
  - ohpc-intel-impi-perf-tools
  - ohpc-intel-io-libs
  - ohpc-intel-mpich-io-libs
  - ohpc-intel-mpich-parallel-libs
  - ohpc-intel-mpich-perf-tools
  - ohpc-intel-mvapich2-io-libs
  - ohpc-intel-mvapich2-perf-tools
  - ohpc-intel-openmpi3-io-libs
  - ohpc-intel-openmpi3-perf-tools
  - ohpc-intel-perf-tools
  - ohpc-intel-python-libs
  - ohpc-intel-python2-libs
  - ohpc-intel-python3-libs
  - ohpc-intel-runtimes
  - ohpc-intel-serial-libs
  - omb-intel-impi-ohpc
  - omb-intel-mpich-ohpc
  - omb-intel-mvapich2-ohpc
  - omb-intel-openmpi3-ohpc
  - openmpi-intel-ohpc
  - openmpi-psm2-intel-ohpc
  - openmpi3-pmix-slurm-intel-ohpc
  - pdtoolkit-intel-ohpc
  - petsc-intel-impi-ohpc
  - petsc-intel-mpich-ohpc
  - petsc-intel-mvapich2-ohpc
  - petsc-intel-openmpi-ohpc
  - petsc-intel-openmpi3-ohpc
  - phdf5-intel-impi-ohpc
  - phdf5-intel-mpich-ohpc
  - phdf5-intel-mvapich2-ohpc
  - phdf5-intel-openmpi-ohpc
  - phdf5-intel-openmpi3-ohpc
  - plasma-intel-ohpc
  - pnetcdf-intel-impi-ohpc
  - pnetcdf-intel-mpich-ohpc
  - pnetcdf-intel-mvapich2-ohpc
  - pnetcdf-intel-openmpi-ohpc
  - pnetcdf-intel-openmpi3-ohpc
  - ptscotch-intel-impi-ohpc
  - ptscotch-intel-mpich-ohpc
  - ptscotch-intel-mvapich2-ohpc
  - ptscotch-intel-openmpi-ohpc
  - ptscotch-intel-openmpi3-ohpc
  - python-mpi4py-intel-impi-ohpc
  - python-mpi4py-intel-mpich-ohpc
  - python-numpy-intel-ohpc
  - python34-mpi4py-intel-impi-ohpc
  - python34-mpi4py-intel-mpich-ohpc
  - python34-numpy-intel-ohpc
  - scalapack-intel-impi-ohpc
  - scalapack-intel-mpich-ohpc
  - scalapack-intel-mvapich2-ohpc
  - scalapack-intel-openmpi-ohpc
  - scalapack-intel-openmpi3-ohpc
  - scalasca-intel-impi-ohpc
  - scalasca-intel-mpich-ohpc
  - scalasca-intel-mvapich2-ohpc
  - scalasca-intel-openmpi-ohpc
  - scalasca-intel-openmpi3-ohpc
  - scorep-intel-impi-ohpc
  - scorep-intel-mpich-ohpc
  - scorep-intel-mvapich2-ohpc
  - scorep-intel-openmpi-ohpc
  - scorep-intel-openmpi3-ohpc
  - scotch-intel-ohpc
  - sionlib-intel-impi-ohpc
  - sionlib-intel-mpich-ohpc
  - sionlib-intel-mvapich2-ohpc
  - sionlib-intel-openmpi-ohpc
  - sionlib-intel-openmpi3-ohpc
  - slepc-intel-impi-ohpc
  - slepc-intel-mpich-ohpc
  - slepc-intel-mvapich2-ohpc
  - slepc-intel-openmpi-ohpc
  - slepc-intel-openmpi3-ohpc
  - superlu-intel-ohpc
  - superlu_dist-intel-impi-ohpc
  - superlu_dist-intel-mpich-ohpc
  - superlu_dist-intel-mvapich2-ohpc
  - superlu_dist-intel-openmpi-ohpc
  - superlu_dist-intel-openmpi3-ohpc
  - tau-intel-impi-ohpc
  - tau-intel-mpich-ohpc
  - tau-intel-mvapich2-ohpc
  - tau-intel-openmpi-ohpc
  - tau-intel-openmpi3-ohpc
  - trilinos-intel-impi-ohpc
  - trilinos-intel-mpich-ohpc
  - trilinos-intel-mvapich2-ohpc
  - trilinos-intel-openmpi-ohpc
  - trilinos-intel-openmpi3-ohpc
openhpc_gnu_packages:
  - adios-gnu-impi-ohpc
  - adios-gnu-mpich-ohpc
  - adios-gnu-mvapich2-ohpc
  - adios-gnu-openmpi-ohpc
  - boost-gnu-impi-ohpc
  - boost-gnu-mpich-ohpc
  - boost-gnu-mvapich2-ohpc
  - boost-gnu-openmpi-ohpc
  - fftw-gnu-mpich-ohpc
  - fftw-gnu-mvapich2-ohpc
  - fftw-gnu-openmpi-ohpc
  - gnu-compilers-ohpc
  - gsl-gnu-ohpc
  - hdf5-gnu-ohpc
  - hypre-gnu-impi-ohpc
  - hypre-gnu-mpich-ohpc
  - hypre-gnu-mvapich2-ohpc
  - hypre-gnu-openmpi-ohpc
  - imb-gnu-impi-ohpc
  - imb-gnu-mpich-ohpc
  - imb-gnu-mvapich2-ohpc
  - imb-gnu-openmpi-ohpc
  - metis-gnu-ohpc
  - mpiP-gnu-impi-ohpc
  - mpiP-gnu-mpich-ohpc
  - mpiP-gnu-mvapich2-ohpc
  - mpiP-gnu-openmpi-ohpc
  - mpich-gnu-ohpc
  - mumps-gnu-impi-ohpc
  - mumps-gnu-mpich-ohpc
  - mumps-gnu-mvapich2-ohpc
  - mumps-gnu-openmpi-ohpc
  - mvapich2-gnu-ohpc
  - netcdf-cxx-gnu-impi-ohpc
  - netcdf-cxx-gnu-mpich-ohpc
  - netcdf-cxx-gnu-mvapich2-ohpc
  - netcdf-cxx-gnu-openmpi-ohpc
  - netcdf-fortran-gnu-impi-ohpc
  - netcdf-fortran-gnu-mpich-ohpc
  - netcdf-fortran-gnu-mvapich2-ohpc
  - netcdf-fortran-gnu-openmpi-ohpc
  - netcdf-gnu-impi-ohpc
  - netcdf-gnu-mpich-ohpc
  - netcdf-gnu-mvapich2-ohpc
  - netcdf-gnu-openmpi-ohpc
  - ocr-gnu-ohpc
  - openblas-gnu-ohpc
  - openmpi-gnu-ohpc
  - pdtoolkit-gnu-ohpc
  - petsc-gnu-impi-ohpc
  - petsc-gnu-mpich-ohpc
  - petsc-gnu-mvapich2-ohpc
  - petsc-gnu-openmpi-ohpc
  - phdf5-gnu-impi-ohpc
  - phdf5-gnu-mpich-ohpc
  - phdf5-gnu-mvapich2-ohpc
  - phdf5-gnu-openmpi-ohpc
  - python-numpy-gnu-ohpc
  - python-scipy-gnu-mpich-ohpc
  - python-scipy-gnu-mvapich2-ohpc
  - python-scipy-gnu-openmpi-ohpc
  - scalapack-gnu-impi-ohpc
  - scalapack-gnu-mpich-ohpc
  - scalapack-gnu-mvapich2-ohpc
  - scalapack-gnu-openmpi-ohpc
  - scalasca-gnu-impi-ohpc
  - scalasca-gnu-mpich-ohpc
  - scalasca-gnu-mvapich2-ohpc
  - scalasca-gnu-openmpi-ohpc
  - scorep-gnu-impi-ohpc
  - scorep-gnu-mpich-ohpc
  - scorep-gnu-mvapich2-ohpc
  - scorep-gnu-openmpi-ohpc
  - sionlib-gnu-impi-ohpc
  - sionlib-gnu-mpich-ohpc
  - sionlib-gnu-mvapich2-ohpc
  - sionlib-gnu-openmpi-ohpc
  - superlu-gnu-ohpc
  - superlu_dist-gnu-impi-ohpc
  - superlu_dist-gnu-mpich-ohpc
  - superlu_dist-gnu-mvapich2-ohpc
  - superlu_dist-gnu-openmpi-ohpc
  - tau-gnu-impi-ohpc
  - tau-gnu-mpich-ohpc
  - tau-gnu-mvapich2-ohpc
  - tau-gnu-openmpi-ohpc
  - trilinos-gnu-impi-ohpc
  - trilinos-gnu-mpich-ohpc
  - trilinos-gnu-mvapich2-ohpc
  - trilinos-gnu-openmpi-ohpc
openhpc_gnu7_packages:
  - R-gnu7-ohpc
  - adios-gnu7-impi-ohpc
  - adios-gnu7-mpich-ohpc
  - adios-gnu7-mvapich2-ohpc
  - adios-gnu7-openmpi-ohpc
  - adios-gnu7-openmpi3-ohpc
  - boost-gnu7-impi-ohpc
  - boost-gnu7-mpich-ohpc
  - boost-gnu7-mvapich2-ohpc
  - boost-gnu7-openmpi-ohpc
  - boost-gnu7-openmpi3-ohpc
  - fftw-gnu7-mpich-ohpc
  - fftw-gnu7-mvapich2-ohpc
  - fftw-gnu7-openmpi-ohpc
  - fftw-gnu7-openmpi3-ohpc
  - gnu7-compilers-ohpc
  - gsl-gnu7-ohpc
  - hdf5-gnu7-ohpc
  - hypre-gnu7-impi-ohpc
  - hypre-gnu7-mpich-ohpc
  - hypre-gnu7-mvapich2-ohpc
  - hypre-gnu7-openmpi-ohpc
  - hypre-gnu7-openmpi3-ohpc
  - imb-gnu7-impi-ohpc
  - imb-gnu7-mpich-ohpc
  - imb-gnu7-mvapich2-ohpc
  - imb-gnu7-openmpi-ohpc
  - imb-gnu7-openmpi3-ohpc
  - likwid-gnu7-ohpc
  - lmod-defaults-gnu7-impi-ohpc
  - lmod-defaults-gnu7-mpich-ohpc
  - lmod-defaults-gnu7-mvapich2-ohpc
  - lmod-defaults-gnu7-openmpi-ohpc
  - lmod-defaults-gnu7-openmpi3-ohpc
  - metis-gnu7-ohpc
  - mfem-gnu7-impi-ohpc
  - mfem-gnu7-mpich-ohpc
  - mfem-gnu7-mvapich2-ohpc
  - mfem-gnu7-openmpi3-ohpc
  - mpiP-gnu7-impi-ohpc
  - mpiP-gnu7-mpich-ohpc
  - mpiP-gnu7-mvapich2-ohpc
  - mpiP-gnu7-openmpi-ohpc
  - mpiP-gnu7-openmpi3-ohpc
  - mpich-gnu7-ohpc
  - mumps-gnu7-impi-ohpc
  - mumps-gnu7-mpich-ohpc
  - mumps-gnu7-mvapich2-ohpc
  - mumps-gnu7-openmpi-ohpc
  - mumps-gnu7-openmpi3-ohpc
  - mvapich2-gnu7-ohpc
  - netcdf-cxx-gnu7-impi-ohpc
  - netcdf-cxx-gnu7-mpich-ohpc
  - netcdf-cxx-gnu7-mvapich2-ohpc
  - netcdf-cxx-gnu7-openmpi-ohpc
  - netcdf-cxx-gnu7-openmpi3-ohpc
  - netcdf-fortran-gnu7-impi-ohpc
  - netcdf-fortran-gnu7-mpich-ohpc
  - netcdf-fortran-gnu7-openmpi-ohpc
  - netcdf-gnu7-impi-ohpc
  - netcdf-gnu7-mpich-ohpc
  - netcdf-gnu7-mvapich2-ohpc
  - netcdf-gnu7-openmpi-ohpc
  - netcdf-gnu7-openmpi3-ohpc
  - ocr-gnu7-ohpc
  - openblas-gnu7-ohpc
  - openmpi-gnu7-ohpc
  - openmpi-psm2-gnu7-ohpc
  - openmpi3-pmix-slurm-gnu7-ohpc
  - pdtoolkit-gnu7-ohpc
  - petsc-gnu7-impi-ohpc
  - petsc-gnu7-mpich-ohpc
  - petsc-gnu7-mvapich2-ohpc
  - petsc-gnu7-openmpi-ohpc
  - petsc-gnu7-openmpi3-ohpc
  - phdf5-gnu7-impi-ohpc
  - phdf5-gnu7-mpich-ohpc
  - phdf5-gnu7-mvapich2-ohpc
  - phdf5-gnu7-openmpi-ohpc
  - phdf5-gnu7-openmpi3-ohpc
  - plasma-gnu7-ohpc
  - pnetcdf-gnu7-impi-ohpc
  - pnetcdf-gnu7-mpich-ohpc
  - pnetcdf-gnu7-mvapich2-ohpc
  - pnetcdf-gnu7-openmpi-ohpc
  - pnetcdf-gnu7-openmpi3-ohpc
  - ptscotch-gnu7-impi-ohpc
  - ptscotch-gnu7-mpich-ohpc
  - ptscotch-gnu7-mvapich2-ohpc
  - ptscotch-gnu7-openmpi-ohpc
  - ptscotch-gnu7-openmpi3-ohpc
  - python-mpi4py-gnu7-impi-ohpc
  - python-mpi4py-gnu7-mpich-ohpc
  - python-mpi4py-gnu7-mvapich2-ohpc
  - python-mpi4py-gnu7-openmpi3-ohpc
  - python-numpy-gnu7-ohpc
  - python-scipy-gnu7-mpich-ohpc
  - python-scipy-gnu7-mvapich2-ohpc
  - python-scipy-gnu7-openmpi-ohpc
  - python-scipy-gnu7-openmpi3-ohpc
  - python34-mpi4py-gnu7-impi-ohpc
  - python34-mpi4py-gnu7-mpich-ohpc
  - python34-numpy-gnu7-ohpc
  - python34-scipy-gnu7-mpich-ohpc
  - scalapack-gnu7-impi-ohpc
  - scalapack-gnu7-mpich-ohpc
  - scalapack-gnu7-mvapich2-ohpc
  - scalapack-gnu7-openmpi-ohpc
  - scalapack-gnu7-openmpi3-ohpc
  - scalasca-gnu7-impi-ohpc
  - scalasca-gnu7-mpich-ohpc
  - scalasca-gnu7-mvapich2-ohpc
  - scalasca-gnu7-openmpi-ohpc
  - scalasca-gnu7-openmpi3-ohpc
  - scorep-gnu7-impi-ohpc
  - scorep-gnu7-mpich-ohpc
  - scorep-gnu7-mvapich2-ohpc
  - scorep-gnu7-openmpi-ohpc
  - scorep-gnu7-openmpi3-ohpc
  - scotch-gnu7-ohpc
  - sionlib-gnu7-impi-ohpc
  - sionlib-gnu7-mpich-ohpc
  - sionlib-gnu7-mvapich2-ohpc
  - sionlib-gnu7-openmpi-ohpc
  - sionlib-gnu7-openmpi3-ohpc
  - slepc-gnu7-impi-ohpc
  - slepc-gnu7-mpich-ohpc
  - slepc-gnu7-mvapich2-ohpc
  - slepc-gnu7-openmpi-ohpc
  - slepc-gnu7-openmpi3-ohpc
  - superlu-gnu7-ohpc
  - superlu_dist-gnu7-impi-ohpc
  - superlu_dist-gnu7-mpich-ohpc
  - superlu_dist-gnu7-mvapich2-ohpc
  - superlu_dist-gnu7-openmpi-ohpc
  - superlu_dist-gnu7-openmpi3-ohpc
  - tau-gnu7-impi-ohpc
  - tau-gnu7-mpich-ohpc
  - tau-gnu7-mvapich2-ohpc
  - tau-gnu7-openmpi-ohpc
  - tau-gnu7-openmpi3-ohpc
  - trilinos-gnu7-impi-ohpc
  - trilinos-gnu7-mpich-ohpc
  - trilinos-gnu7-mvapich2-ohpc
  - trilinos-gnu7-openmpi-ohpc
  - trilinos-gnu7-openmpi3-ohpc
openhpc_gnu8_packages:
  - R-gnu8-ohpc
  - adios-gnu8-impi-ohpc
  - adios-gnu8-mpich-ohpc
  - adios-gnu8-mvapich2-ohpc
  - adios-gnu8-openmpi3-ohpc
  - boost-gnu8-impi-ohpc
  - boost-gnu8-mpich-ohpc
  - boost-gnu8-mvapich2-ohpc
  - boost-gnu8-openmpi3-ohpc
  - dimemas-gnu8-impi-ohpc
  - dimemas-gnu8-mpich-ohpc
  - dimemas-gnu8-mvapich2-ohpc
  - dimemas-gnu8-openmpi3-ohpc
  - extrae-gnu8-impi-ohpc
  - extrae-gnu8-mpich-ohpc
  - extrae-gnu8-mvapich2-ohpc
  - extrae-gnu8-openmpi3-ohpc
  - fftw-gnu8-mpich-ohpc
  - fftw-gnu8-mvapich2-ohpc
  - fftw-gnu8-openmpi3-ohpc
  - geopm-gnu8-impi-ohpc
  - geopm-gnu8-mpich-ohpc
  - geopm-gnu8-mvapich2-ohpc
  - geopm-gnu8-openmpi3-ohpc
  - gnu8-compilers-ohpc
  - gsl-gnu8-ohpc
  - hdf5-gnu8-ohpc
  - hypre-gnu8-impi-ohpc
  - hypre-gnu8-mpich-ohpc
  - hypre-gnu8-mvapich2-ohpc
  - hypre-gnu8-openmpi3-ohpc
  - imb-gnu8-impi-ohpc
  - imb-gnu8-mpich-ohpc
  - imb-gnu8-mvapich2-ohpc
  - imb-gnu8-openmpi3-ohpc
  - likwid-gnu8-ohpc
  - metis-gnu8-ohpc
  - mfem-gnu8-impi-ohpc
  - mfem-gnu8-mpich-ohpc
  - mfem-gnu8-mvapich2-ohpc
  - mfem-gnu8-openmpi3-ohpc
  - mpiP-gnu8-impi-ohpc
  - mpiP-gnu8-mpich-ohpc
  - mpiP-gnu8-mvapich2-ohpc
  - mpiP-gnu8-openmpi3-ohpc
  - mpich-gnu8-ohpc
  - mumps-gnu8-impi-ohpc
  - mumps-gnu8-mpich-ohpc
  - mumps-gnu8-mvapich2-ohpc
  - mumps-gnu8-openmpi3-ohpc
  - mvapich2-gnu8-ohpc
  - netcdf-cxx-gnu8-impi-ohpc
  - netcdf-cxx-gnu8-mpich-ohpc
  - netcdf-cxx-gnu8-mvapich2-ohpc
  - netcdf-cxx-gnu8-openmpi3-ohpc
  - netcdf-fortran-gnu8-impi-ohpc
  - netcdf-fortran-gnu8-mpich-ohpc
  - netcdf-gnu8-impi-ohpc
  - netcdf-gnu8-mpich-ohpc
  - netcdf-gnu8-mvapich2-ohpc
  - netcdf-gnu8-openmpi3-ohpc
  - ocr-gnu8-ohpc
  - ohpc-gnu8-geopm
  - ohpc-gnu8-io-libs
  - ohpc-gnu8-mpich-io-libs
  - ohpc-gnu8-mpich-parallel-libs
  - ohpc-gnu8-mpich-perf-tools
  - ohpc-gnu8-mvapich2-io-libs
  - ohpc-gnu8-mvapich2-parallel-libs
  - ohpc-gnu8-mvapich2-perf-tools
  - ohpc-gnu8-openmpi3-io-libs
  - ohpc-gnu8-openmpi3-parallel-libs
  - ohpc-gnu8-openmpi3-perf-tools
  - ohpc-gnu8-parallel-libs
  - ohpc-gnu8-perf-tools
  - ohpc-gnu8-python-libs
  - ohpc-gnu8-python2-libs
  - ohpc-gnu8-python3-libs
  - ohpc-gnu8-runtimes
  - ohpc-gnu8-serial-libs
  - omb-gnu8-impi-ohpc
  - omb-gnu8-mpich-ohpc
  - omb-gnu8-mvapich2-ohpc
  - omb-gnu8-openmpi3-ohpc
  - openblas-gnu8-ohpc
  - opencoarrays-gnu8-impi-ohpc
  - opencoarrays-gnu8-mpich-ohpc
  - opencoarrays-gnu8-mvapich2-ohpc
  - opencoarrays-gnu8-openmpi3-ohpc
  - openmpi3-pmix-slurm-gnu8-ohpc
  - pdtoolkit-gnu8-ohpc
  - petsc-gnu8-impi-ohpc
  - petsc-gnu8-mpich-ohpc
  - petsc-gnu8-mvapich2-ohpc
  - petsc-gnu8-openmpi3-ohpc
  - phdf5-gnu8-impi-ohpc
  - phdf5-gnu8-mpich-ohpc
  - phdf5-gnu8-mvapich2-ohpc
  - phdf5-gnu8-openmpi3-ohpc
  - plasma-gnu8-ohpc
  - pnetcdf-gnu8-impi-ohpc
  - pnetcdf-gnu8-mpich-ohpc
  - pnetcdf-gnu8-mvapich2-ohpc
  - pnetcdf-gnu8-openmpi3-ohpc
  - ptscotch-gnu8-impi-ohpc
  - ptscotch-gnu8-mpich-ohpc
  - ptscotch-gnu8-mvapich2-ohpc
  - ptscotch-gnu8-openmpi3-ohpc
  - python-mpi4py-gnu8-impi-ohpc
  - python-mpi4py-gnu8-mpich-ohpc
  - python-mpi4py-gnu8-mvapich2-ohpc
  - python-mpi4py-gnu8-openmpi3-ohpc
  - python-numpy-gnu8-ohpc
  - python-scipy-gnu8-mpich-ohpc
  - python-scipy-gnu8-mvapich2-ohpc
  - python-scipy-gnu8-openmpi3-ohpc
  - python34-mpi4py-gnu8-impi-ohpc
  - python34-mpi4py-gnu8-mpich-ohpc
  - python34-numpy-gnu8-ohpc
  - python34-scipy-gnu8-mpich-ohpc
  - scalapack-gnu8-impi-ohpc
  - scalapack-gnu8-mpich-ohpc
  - scalapack-gnu8-mvapich2-ohpc
  - scalapack-gnu8-openmpi3-ohpc
  - scalasca-gnu8-impi-ohpc
  - scalasca-gnu8-mpich-ohpc
  - scalasca-gnu8-mvapich2-ohpc
  - scalasca-gnu8-openmpi3-ohpc
  - scorep-gnu8-impi-ohpc
  - scorep-gnu8-mpich-ohpc
  - scorep-gnu8-mvapich2-ohpc
  - scorep-gnu8-openmpi3-ohpc
  - scotch-gnu8-ohpc
  - sionlib-gnu8-impi-ohpc
  - sionlib-gnu8-mpich-ohpc
  - sionlib-gnu8-mvapich2-ohpc
  - sionlib-gnu8-openmpi3-ohpc
  - slepc-gnu8-impi-ohpc
  - slepc-gnu8-mpich-ohpc
  - slepc-gnu8-mvapich2-ohpc
  - slepc-gnu8-openmpi3-ohpc
  - superlu-gnu8-ohpc
  - superlu_dist-gnu8-impi-ohpc
  - superlu_dist-gnu8-mpich-ohpc
  - superlu_dist-gnu8-mvapich2-ohpc
  - superlu_dist-gnu8-openmpi3-ohpc
  - tau-gnu8-impi-ohpc
  - tau-gnu8-mpich-ohpc
  - tau-gnu8-mvapich2-ohpc
  - tau-gnu8-openmpi3-ohpc
  - trilinos-gnu8-impi-ohpc
  - trilinos-gnu8-mpich-ohpc
  - trilinos-gnu8-mvapich2-ohpc
  - trilinos-gnu8-openmpi3-ohpc
