---
# vars file for ood-portal

ldap_hosts:
  - 'controller.cluster'

ood_portal_cfg_path: /etc/ood/config/

cluster_name: Gwydion
slurm_controller: controller.cluster
login_host: controller.cluster
enable_vnc_to_nodes: false
vnc_idle_timeout: 180
vnc_desktop: xfce

ood_portal_brand:

ood_welcome_text_branding:
  vscaler:
    - '<style>.hp_intro img {width:100%; text-align:center} .color1 {background-color:#ed553b; color:white; min-height:220px} .color2 {background-color:#fee329; min-height:220px} .color3 {background-color:#e7e7e7; color:black} .padded{padding:50px} .padded-sm {padding:10px} .margin-sm {margin:20px 0px 0px 0px} .color1 a {color:white} .intro-vid {background:url(/public/intro-vid.jpg); background-position-y:center; color:white} .footer-logo {display:none}</style><p class="hp_intro">%{logo_img_tag}</p>'
    - '<p class="col-md-12 lead color3 padded">Welcome to the vScaler Cluster portal, providing your with  an integrated, single access point for all of your HPC cloud resources. Having an issue? Contact us for support <button type="button" class="btn btn-warning pull-right margin-sm padded-sm">CONTACT SUPPORT</button></p><p class="lead color1 padded col-md-5"><strong>Useful links:</strong><br /><a href="#">&#62; Read the Docs</a><br /><a href="#">&#62; Shell Access</a><br /><a href="#">&#62; Cluster portal shortcuts</a></p><p class="col-md-7 padded color2 lead intro-vid pull-right"><strong>Watch the video</strong><br />Start your cloud journey today.<br /><br />Introduction to vScaler Cluster portal &#62;<br /></p>'

ood_pun_custom_env_branding:
  vscaler: |
    pun_custom_env:
      OOD_DASHBOARD_TITLE: "vScaler Cluster Portal2"
      OOD_BRAND_BG_COLOR: "#f8f8f8"
      OOD_BRAND_LINK_ACTIVE_BG_COLOR: "#f2bb02"
      OOD_DASHBOARD_LOGO: "/public/vscaler_header.jpg"
      OOD_DASBOARD_HEADER_IMG_LOGO: "/public/vscaler_logo_padded.png"
      OOD_NAVBAR_TYPE: "default"