---
# tasks file for ood-portal
- name: Install centos-release-scl repo
  yum:
    name: centos-release-scl
    state: present

- name: Install OOD Repo rpm
  yum:
    name: https://yum.osc.edu/ondemand/1.6/ondemand-release-web-1.6-1.el7.noarch.rpm
    state: present

- name: Install OOD
  yum:
    name: ondemand
    state: present

- name: Ensure ood config paths exist
  file:
    path: '{{ item }}'
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - '/etc/ood/config/'
    - '/etc/ood/config/clusters.d'
    - '/etc/ood/config/apps'
    - '/etc/ood/config/apps/bc_desktop'

- name: Render ood_portal config file
  template:
    src: 'ood_portal.yml'
    dest: '{{ ood_portal_cfg_path }}/ood_portal.yml'
    mode: '0644'
    owner: root
    group: root

- name: listen on port 8080 if we are on the controller node
  lineinfile:
    path: '{{ ood_portal_cfg_path }}/ood_portal.yml'
    line: 'port=8080'
    state: present
  when: '"controllers" in group_names'

- name: remove default apache pages
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /opt/rh/httpd24/root/etc/httpd/conf.d/welcome.conf
    - /opt/rh/httpd24/root/etc/httpd/conf.d/userdir.conf
    - /opt/rh/httpd24/root/etc/httpd/conf.d/ssl.conf
    - /opt/rh/httpd24/root/etc/httpd/conf.d/autoindex.conf

- name: do not listen on port 8080 if we are not on the controller node
  lineinfile:
    path: '{{ ood_portal_cfg_path }}/ood_portal.yml'
    line: 'port=8080'
    state: absent
  when: '"controllers" not in group_names'

- name: Render ood_portal cluster config file
  template:
    src: 'cluster_definition.yml'
    dest: '{{ ood_portal_cfg_path }}/clusters.d/{{ cluster_name }}.yml'
    mode: '0644'
    owner: root
    group: root

- name: Render ood_portal remote_desktop config file
  template:
    src: 'bc_desktop_definition.yml'
    dest: '{{ ood_portal_cfg_path }}/apps/bc_desktop/{{ cluster_name }}.yml'
    mode: '0644'
    owner: root
    group: root
    backup: yes
  when: enable_vnc_to_nodes == true

- name: Copy vscaler branding  to /var/www/ood/public 
  copy:
    src: vscaler/{{ item }}
    dest: /var/www/ood/public/{{ item }}
  with_items:
    - favicon.ico
    - intro-vid.jpg
    - logo_color_black_padded.png
    - vscaler_header.jpg
  when: ood_portal_brand == "vscaler"

- name: Apply vscaler welcome_html branding if appropriate
  replace:
    path: '/var/www/ood/apps/sys/dashboard/config/locales/en.yml'
    regexp: '(    welcome_html: |\n)(      .+\n)+'
    replace: '\1      {{ ood_welcome_text_branding.vscaler|join("\n      ")}}\n'
  when: ood_portal_brand == "vscaler"

- name: Apply vscaler pun_custom_env branding if appropriate
  blockinfile:
    path: 'etc/ood/config/nginx_stage.yml'
    block: '{{ ood_pun_custom_env_branding.vscaler }}'
    marker: "# {mark} ANSIBLE MANAGED BLOCK for pun_custom_env"
  when: '"cloudcontroller" not in group_names'

- name: run update_ood_portal to generate webserver config file
  command: '/opt/ood/ood-portal-generator/sbin/update_ood_portal'
  register: command_result
  failed_when: "'Completed successfully!' not in command_result.stdout"

- name: enable ood webserver by default
  service:
    name: httpd24-httpd
    enabled: yes

- name: (re)start ood webserver
  service:
    name: httpd24-httpd
    state: restarted